spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/turbo
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true